# Generated by Django 5.1.1 on 2024-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_lastname_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lead',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='media_footer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
