# Generated by Django 5.1.1 on 2024-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
